title: This is my title
author: R Saunders
email: Saunders1732@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  this is my generic description

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
